clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file:
    - 'osu.Framework\osu.Framework.csproj'
    - 'osu.Framework.Android\osu.Framework.Android.csproj'
    - 'osu.Framework.iOS\osu.Framework.iOS.csproj'
  version: '0.0.{build}'
cache:
  - '%LOCALAPPDATA%\NuGet\v3-cache -> appveyor.yml'
before_build:
  - ps: dotnet --info # Useful when version mismatch between CI and local
  - ps: nuget restore -verbosity quiet # Only nuget.exe knows both new (.NET Core) and old (Xamarin) projects
build:
  project: osu-framework.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
after_build:
  - ps: dotnet tool restore
  - ps: dotnet format --dry-run --check
test:
  assemblies:
    except:
      - '**\*Android*'
      - '**\*iOS*'
      - 'build\**\*'
